"""End4

Revision ID: 16274bda3b4e
Revises: daddef4d5080
Create Date: 2023-01-16 11:48:04.660172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16274bda3b4e'
down_revision = 'daddef4d5080'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
