"""End9

Revision ID: 18d08a0fe31f
Revises: a619b4247931
Create Date: 2023-01-16 12:13:29.290026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d08a0fe31f'
down_revision = 'a619b4247931'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
