"""End7

Revision ID: 476e4f1bd829
Revises: d4c7d6984fe0
Create Date: 2023-01-16 11:56:01.564359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '476e4f1bd829'
down_revision = 'd4c7d6984fe0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'dish_in_submenu', sa.Column(
            'dishes', postgresql.UUID(), nullable=True,
        ),
    )
    op.drop_constraint(
        'dish_in_submenu_dish_key',
        'dish_in_submenu', type_='unique',
    )
    op.create_unique_constraint(None, 'dish_in_submenu', ['dishes'])
    op.drop_constraint(
        'dish_in_submenu_dish_fkey',
        'dish_in_submenu', type_='foreignkey',
    )
    op.create_foreign_key(None, 'dish_in_submenu', 'dish', ['dishes'], ['id'])
    op.drop_column('dish_in_submenu', 'dish')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'dish_in_submenu', sa.Column(
            'dish', postgresql.UUID(), autoincrement=False, nullable=True,
        ),
    )
    op.drop_constraint(None, 'dish_in_submenu', type_='foreignkey')
    op.create_foreign_key(
        'dish_in_submenu_dish_fkey',
        'dish_in_submenu', 'dish', ['dish'], ['id'],
    )
    op.drop_constraint(None, 'dish_in_submenu', type_='unique')
    op.create_unique_constraint(
        'dish_in_submenu_dish_key', 'dish_in_submenu', ['dish'],
    )
    op.drop_column('dish_in_submenu', 'dishes')
    # ### end Alembic commands ###
