"""End5

Revision ID: 731f4e479e08
Revises: 16274bda3b4e
Create Date: 2023-01-16 11:50:20.334233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '731f4e479e08'
down_revision = '16274bda3b4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
