"""End

Revision ID: 76f48a71efcc
Revises: ba33fbd526b1
Create Date: 2023-01-16 11:21:13.823936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76f48a71efcc'
down_revision = 'ba33fbd526b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
