"""empty message

Revision ID: 86b31957f4e5
Revises: 18d08a0fe31f
Create Date: 2023-01-20 19:03:13.126456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86b31957f4e5'
down_revision = '18d08a0fe31f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
