"""End2

Revision ID: 9715ef86162f
Revises: b0577fdcb325
Create Date: 2023-01-16 11:44:36.791562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9715ef86162f'
down_revision = 'b0577fdcb325'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
