"""End8

Revision ID: a619b4247931
Revises: 476e4f1bd829
Create Date: 2023-01-16 12:04:06.308817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a619b4247931'
down_revision = '476e4f1bd829'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
