"""End1

Revision ID: b0577fdcb325
Revises: b4b892822f05
Create Date: 2023-01-16 11:28:06.644793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0577fdcb325'
down_revision = 'b4b892822f05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
