"""Second

Revision ID: ba33fbd526b1
Revises: d71c0738fd5f
Create Date: 2023-01-16 11:19:56.809599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba33fbd526b1'
down_revision = 'd71c0738fd5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
