"""End3

Revision ID: daddef4d5080
Revises: 9715ef86162f
Create Date: 2023-01-16 11:46:31.904499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daddef4d5080'
down_revision = '9715ef86162f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
